version: '3.8'

services:
  # Service PostgreSQL pour Sequelize
  db:
    image: postgres:14
    container_name: tiktok_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: votremotdepasse
      POSTGRES_DB: tiktok_clone
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

  # Service Redis pour la mise en cache
  redis:
    image: redis:7
    container_name: tiktok_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped
    command: redis-server --appendonly yes

  # Optionnel : Service pour l'interface Redis
  redis-commander:
    image: rediscommander/redis-commander:latest
    container_name: tiktok_redis_ui
    environment:
      - REDIS_HOSTS=local:redis:6379
    ports:
      - "8081:8081"
    depends_on:
      - redis
    restart: unless-stopped

  # Optionnel : Service pour l'interface PostgreSQL
  adminer:
    image: adminer:latest
    container_name: tiktok_db_ui
    ports:
      - "8080:8080"
    depends_on:
      - db
    restart: unless-stopped

  # Service pour le stockage de fichiers vidéo (MinIO, compatible S3)
  minio:
    image: minio/minio:latest
    container_name: tiktok_storage
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio123
    ports:
      - "9000:9000"  # API
      - "9001:9001"  # Console
    volumes:
      - minio_data:/data
    command: server /data --console-address ":9001"
    restart: unless-stopped

  # Définir votre backend Node.js avec Sequelize
  # Décommentez cette section une fois que votre backend est prêt
  # backend:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   container_name: tiktok_backend
  #   ports:
  #     - "3000:3000"
  #   depends_on:
  #     - db
  #     - redis
  #     - minio
  #   volumes:
  #     - ./:/app
  #     - /app/node_modules
  #   environment:
  #     NODE_ENV: development
  #     DB_HOST: db
  #     DB_USER: postgres
  #     DB_PASS: votremotdepasse
  #     DB_NAME: tiktok_clone
  #     REDIS_HOST: redis
  #     REDIS_PORT: 6379
  #     MINIO_ENDPOINT: minio
  #     MINIO_PORT: 9000
  #     MINIO_ACCESS_KEY: minio
  #     MINIO_SECRET_KEY: minio123
  #   restart: unless-stopped

volumes:
  postgres_data:
  redis_data:
  minio_data: